# Generated by Django 5.2.13 on 2026-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecard',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
